Release html minify [issue #32]
LunchDevCommunity/community-calendar pull request #33
Opened 2021-01-18 23:24 UTC by Kirill-frontend

Features:
The functionality was made with minification of the html file,
when using different scripts
-----------------------------------
Changelog: 
Edit package.json (in scripts)
Install two packages (cross-env, eleventy-plugin-files-minifier)
Edit .eleventy.js
---------------------------------------
P.S. 
I'm new. I would be grateful for advice

2021-01-18 23:40 UTC, msutkowski requested changes
Looks good! Just a small suggestion.

2021-01-18 23:40 UTC, msutkowski commented on .eleventy.js
> +const isProduction = process.env.NODE_ENV || false;
```suggestion
const isProduction = process.env.NODE_ENV === 'production';
```

2021-01-18 23:40 UTC, msutkowski commented on .eleventy.js
> +	if (isProduction === 'production') {
```suggestion
	if (isProduction) {
```

2021-01-18 23:45 UTC, BenDMyers commented
@Kirill-frontend This looks great! Thank you so much for taking this on!

I agree with @msutkowski's review above. Would you be willing to make that change for us?

2021-01-19 14:07 UTC, Kirill-frontend commented
Yes, i can.

2021-01-19 14:33 UTC, BenDMyers commented
This looks great, @Kirill-frontend! I'm going to go ahead and merge this in now. Thank you so much for pulling in this work!

2021-01-19 14:34 UTC, BenDMyers approved these changes

2021-01-19 14:34 UTC, merged

2021-01-19 16:26 UTC, chantastic commented
Thanks @Kirill-frontend! This is a really great optimization PR 🙏

2021-01-23 22:11 UTC, BenDMyers commented
@all-contributors Please add @Kirill-frontend for code.